import { BASE_APP_URL, BROWSER_SERVICE_HOST, BROWSER_SERVICE_PORT } from '$env/static/private';
import { AppName } from '$lib/api/configurations/common';
import type { RemoteBrwoserServiceLoadStatusResponse } from '$lib/types/remote-browser';

const baseUrl = `http://${BROWSER_SERVICE_HOST}:${BROWSER_SERVICE_PORT}`;

function createHeaderTemplate(formName: string): string {
	return `
		<div style="width: 100%; box-sizing: border-box; padding: 6px 38px; font-family: 'Helvetica', 'Arial', sans-serif; display: flex; align-items: center; justify-content: center; border-bottom: 1px solid #e5e7eb; -webkit-print-color-adjust: exact; print-color-adjust: exact;">
			<div style="font-weight: 600; font-size: 9px; letter-spacing: 0.5px; color: #9ca3af;">${formName}</div>
		</div>
	`;
}

function createFooterTemplate(): string {
	return `
		<div style="width: 100%; box-sizing: border-box; padding: 6px 38px; font-family: 'Helvetica', 'Arial', sans-serif; font-size: 8px; border-top: 1px solid #e5e7eb; display: grid; grid-template-columns: 1fr auto 1fr; align-items: center; color: #9ca3af; -webkit-print-color-adjust: exact; print-color-adjust: exact;">
			<div style="text-align: left;">Generated by <span style="font-weight: 600; color: #6b7280;">${AppName}</span></div>
			<div style="text-align: center;"><span class="date"></span></div>
			<div style="text-align: right;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
		</div>
	`;
}
interface CreatePdfParameters {
	formPublicLinkIndentifier: string;
	formId: number;
	formName: string;
	submissionCandidateDataId: number;
}
function createPdfParameters(parameters: CreatePdfParameters) {
	return {
		url: `${BASE_APP_URL}/r/${parameters.formPublicLinkIndentifier}?candidateDataId=${parameters.submissionCandidateDataId}`,
		webhook: {
			url: `${BASE_APP_URL}/api/webhooks/forms/${parameters.formId}/process`,
			customPayload: {
				submissionCandidateDataId: parameters.submissionCandidateDataId
			}
		},
		containerClass: 'form',
		options: {
			displayHeaderFooter: true,
			printBackground: true,
			headerTemplate: createHeaderTemplate(parameters.formName),
			footerTemplate: createFooterTemplate(),
			margin: {
				top: '25mm',
				bottom: '25mm',
				left: '10mm',
				right: '10mm'
			}
		}
	};
}

export const requestPdfCreation = async (parameters: CreatePdfParameters): Promise<boolean> => {
	const res = await fetch(`${baseUrl}/pdf`, {
		method: 'POST',
		body: JSON.stringify(createPdfParameters(parameters))
	});
	if (!res?.ok) return false;
	const response = await res.json();
	console.log('[Request PDF creation]', response.message);
	return true;
};

export const requestLoadStatus = async (): Promise<
	RemoteBrwoserServiceLoadStatusResponse | undefined
> => {
	const res = await fetch(`${baseUrl}/load`);
	if (!res?.ok) return;
	const response = await res.json();
	return response;
};

export const requestToPrepare = async (): Promise<boolean> => {
	const res = await fetch(`${baseUrl}/load/prepare`, { method: 'POST' });
	return !!res?.ok;
};
